[versions]
agp = "8.9.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
testng = "7.9.0"
appium = "9.0.0"
testngVersion = "6.9.6"
selenium = "4.1.2"


[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
testng = { module = "org.testng:testng", version.ref = "testng" }
appium = { module = "io.appium:java-client", version.ref = "appium" }
guava = { module = "com.google.guava:guava", version = "31.1-jre" }
selenium = { module = "org.seleniumhq.selenium:selenium-java", version.ref = "selenium" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

